### ISSUE TITLE
merge request

### ISSUE THREAD

**Issue by mgood7123** [dztall/ccr_resources#25]
https://github.com/mgood7123/MobileC_CCR

(i will display changes from current Mobile C and this repo, as it is easier then comparing urs againsg mine manually trying to keep track of changes from previous versions and current versions of my merges aswell as ur changes)

merged current shell, renamed Built-Ins to builtins

merged current git

new (more stabler) find command

new command : getline : cat implimented with getline

new command: dotgit (moved .git to dotgit if it is present) (kinda like an alias lol), will probably make it a git command instead, like git uninit or something

new command: colors: display a list of supported printable color combinations along with that they actually look like

new command: fecho : like echo but with the option to output to a file

new command: bom : displays wether a file contains a BOM mark or not, and if so displays info such as BOM type, BOM length, and the BOM itself in hex

updated help command: now displays valid commands located in cwd, reinforces the display of VALID executable formats such as .py, .ll, c, and others, now makes SURE that commands that exist in there respective folders are displayed, for example, cp/cp.proj.c, Shell/shell.h, cp will show as a command but Shell will not show as a command, currently obeys the execution rule that it will execute a command in a folder if it is conforms to this syntax: [cmd]/[cmd].proj.c, the rule applies to all locationes searched by help (including the cwd)

new command: ln: creates symlinks (currently useless in ios but would be assumed to work in android)

new command: argv : displays argument count and argument contents

new command: mmaps : (ios only) attempts to emulate [cat /proc/self/maps], unknown wether mappings displayed are correct or if they are garbage but at least it is something

new command: raw : displays raw input in decimal, eg "a is 97' ( usefull for seeing what key codes ur keyboard (3rd party keyboards included) is capable of sending)

**Comment by dztall** [comment]
Ok
